-------------------------------------------------------------------------------
-- Grabungsdatenbank - Export von MS Access nach Sybase SQL
--
-- TABLE           : T_Profilbeschreibung
--
-- EXPORT DATE/TIME: 13.02.2015 12:03:55
-- SOURCE DATA BASE: B:\03_GDBs_AktivitätsNr\2510_Profen_HW-Block\Datenbank\Grabungsdatenbank\GDB.mde  (Created by Access V.4.0)
-- USER            : admin
-- EXPORTED BY     : exportSQLD 2.1 (on Access V.3.6)
-------------------------------------------------------------------------------

-- This table has no data
